spring: 
  data: 
    mongodb: 
      uri: mongodb://mongo:passmongo@mongo.com:30888/admin
  kafka: 
    bootstrap-servers:  test:9411
    consumer: 
      group-id: message-group
    topics: test_topic
  
  sleuth: 
    sampler: 
      probability: 1
LIBERTY_SERVICE_URI:
  uri: http://liberty
MESSAGING:
  topicName: test_topic
SCHEDULER:
  interval: "0/30 0/1 * 1/1 * ? *"
